c19LinksGlobal = [{"country":"Afghanistan","region":"","article":"Afghanistan","chart":"0","table":"","index":"0"},
{"country":"Albania","region":"","article":"Albania","chart":"0","table":"","index":"0"},
{"country":"Algeria","region":"","article":"Algeria","chart":"0","table":"","index":"0"},
{"country":"Andorra","region":"","article":"Andorra","chart":"0","table":"","index":"0"},
{"country":"Angola","region":"","article":"Angola","chart":"0","table":"","index":"0"},
{"country":"Antigua & Barbuda","region":"","article":"Antigua_and_Barbuda","chart":"0","table":"","index":"0"},
{"country":"Argentina","region":"","article":"Argentina","chart":"0","table":"","index":"0"},
{"country":"Armenia","region":"","article":"Armenia","chart":"0","table":"","index":"0"},
{"country":"Australia","region":"Australian Capital Territory","article":"Australian_Capital_Territory","chart":"0","table":"","index":"0"},
{"country":"Australia","region":"New South Wales","article":"Australia","chart":"0","table":"","index":"0"},
{"country":"Australia","region":"Northern Territory","article":"Australia","chart":"0","table":"","index":"0"},
{"country":"Australia","region":"Queensland","article":"Australia","chart":"0","table":"","index":"0"},
{"country":"Australia","region":"South Australia","article":"Australia","chart":"0","table":"","index":"0"},
{"country":"Australia","region":"Tasmania","article":"Australia","chart":"0","table":"","index":"0"},
{"country":"Australia","region":"Victoria","article":"Australia","chart":"0","table":"","index":"0"},
{"country":"Australia","region":"Western Australia","article":"Australia","chart":"0","table":"","index":"0"},
{"country":"Australia","region":"","article":"Australia","chart":"0","table":"","index":"0"},
{"country":"Austria","region":"","article":"Austria","chart":"0","table":"","index":"0"},
{"country":"Azerbaijan","region":"","article":"Azerbaijan","chart":"0","table":"","index":"0"},
{"country":"Bahamas","region":"","article":"Bahamas","chart":"0","table":"","index":"0"},
{"country":"Bahrain","region":"","article":"Bahrain","chart":"0","table":"","index":"0"},
{"country":"Bangladesh","region":"","article":"Bangladesh","chart":"0","table":"","index":"0"},
{"country":"Barbados","region":"","article":"Barbados","chart":"0","table":"","index":"0"},
{"country":"Belarus","region":"","article":"Belarus","chart":"0","table":"","index":"0"},
{"country":"Belgium","region":"","article":"Belgium","chart":"0","table":"","index":"0"},
{"country":"Belize","region":"","article":"Belize","chart":"0","table":"","index":"0"},
{"country":"Benin","region":"","article":"Benin","chart":"0","table":"","index":"0"},
{"country":"Bhutan","region":"","article":"Bhutan","chart":"0","table":"","index":"0"},
{"country":"Bolivia","region":"","article":"Bolivia","chart":"0","table":"","index":"0"},
{"country":"Bosnia & Herzegovina","region":"","article":"Bosnia_and_Herzegovina","chart":"0","table":"","index":"0"},
{"country":"Botswana","region":"","article":"Botswana","chart":"0","table":"","index":"0"},
{"country":"Brazil","region":"","article":"Brazil","chart":"0","table":"","index":"0"},
{"country":"Brunei","region":"","article":"Brunei","chart":"0","table":"","index":"0"},
{"country":"Bulgaria","region":"","article":"Bulgaria","chart":"0","table":"","index":"0"},
{"country":"Burkina Faso","region":"","article":"Burkina_Faso","chart":"0","table":"","index":"0"},
{"country":"Burundi","region":"","article":"Burundi","chart":"0","table":"","index":"0"},
{"country":"Cambodia","region":"","article":"Cambodia","chart":"0","table":"","index":"0"},
{"country":"Cameroon","region":"","article":"Cameroon","chart":"0","table":"","index":"0"},
{"country":"Canada","region":"Alberta","article":"Alberta","chart":"0","table":"","index":"0"},
{"country":"Canada","region":"British Columbia","article":"British_Columbia","chart":"0","table":"","index":"0"},
{"country":"Canada","region":"Grand Princess","article":"Grand_Princess","chart":"0","table":"","index":"0"},
{"country":"Canada","region":"Manitoba","article":"Manitoba","chart":"0","table":"","index":"0"},
{"country":"Canada","region":"New Brunswick","article":"New_Brunswick","chart":"0","table":"","index":"0"},
{"country":"Canada","region":"Newfoundland and Labrador","article":"Newfoundland_and_Labrador","chart":"0","table":"","index":"0"},
{"country":"Canada","region":"Nova Scotia","article":"Nova_Scotia","chart":"0","table":"","index":"0"},
{"country":"Canada","region":"Ontario","article":"Ontario","chart":"0","table":"","index":"0"},
{"country":"Canada","region":"Prince Edward Island","article":"Prince_Edward_Island","chart":"0","table":"","index":"0"},
{"country":"Canada","region":"Quebec","article":"Quebec","chart":"0","table":"","index":"0"},
{"country":"Canada","region":"Saskatchewan","article":"Saskatchewan","chart":"0","table":"","index":"0"},
{"country":"Canada","region":"Northwest Territories","article":"Northwest_Territories","chart":"0","table":"","index":"0"},
{"country":"Canada","region":"Yukon","article":"Yukon","chart":"0","table":"","index":"0"},
{"country":"Canada","region":"","article":"Canada","chart":"0","table":"","index":"0"},
{"country":"Cape Verde","region":"","article":"Cape_Verde","chart":"0","table":"","index":"0"},
{"country":"Central African Republic","region":"","article":"Central_African_Republic","chart":"0","table":"","index":"0"},
{"country":"Chad","region":"","article":"Chad","chart":"0","table":"","index":"0"},
{"country":"Chile","region":"","article":"Chile","chart":"0","table":"","index":"0"},
{"country":"China","region":"Anhui","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Beijing","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Chongqing","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Fujian","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Gansu","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Guangdong","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Guangxi","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Guizhou","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Hainan","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Hebei","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Heilongjiang","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Henan","article":"Henan","chart":"0","table":"","index":"0"},
{"country":"China","region":"Hong Kong","article":"Hong_Kong","chart":"0","table":"","index":"0"},
{"country":"China","region":"Hubei","article":"Hubei","chart":"0","table":"","index":"0"},
{"country":"China","region":"Hunan","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Inner Mongolia","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Jiangsu","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Jiangxi","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Jilin","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Liaoning","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Macau","article":"Macau","chart":"0","table":"","index":"0"},
{"country":"China","region":"Ningxia","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Qinghai","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Shaanxi","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Shandong","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Shanghai","article":"Shanghai","chart":"0","table":"","index":"0"},
{"country":"China","region":"Shanxi","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Sichuan","article":"Sichuan","chart":"0","table":"","index":"0"},
{"country":"China","region":"Tianjin","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Tibet","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Xinjiang","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Yunnan","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"Zhejiang","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"China","region":"","article":"mainland_China","chart":"0","table":"","index":"0"},
{"country":"Colombia","region":"","article":"Colombia","chart":"0","table":"","index":"0"},
{"country":"Republic of the Congo","region":"","article":"Republic_of_the_Congo","chart":"0","table":"","index":"0"},
{"country":"DR Congo","region":"","article":"the_Democratic_Republic_of_the_Congo","chart":"0","table":"","index":"0"},
{"country":"Costa Rica","region":"","article":"Costa_Rica","chart":"0","table":"","index":"0"},
{"country":"Croatia","region":"","article":"Croatia","chart":"0","table":"","index":"0"},
{"country":"Cuba","region":"","article":"Cuba","chart":"0","table":"","index":"0"},
{"country":"Cyprus","region":"","article":"Cyprus","chart":"0","table":"","index":"0"},
{"country":"Czech Republic","region":"","article":"Czech_Republic","chart":"0","table":"","index":"0"},
{"country":"Denmark","region":"Faroe Islands","article":"Faroe_Islands","chart":"0","table":"","index":"0"},
{"country":"Denmark","region":"Greenland","article":"Greenland","chart":"0","table":"","index":"0"},
{"country":"Denmark","region":"","article":"Denmark","chart":"0","table":"","index":"0"},
{"country":"Djibouti","region":"","article":"Djibouti","chart":"0","table":"","index":"0"},
{"country":"Dominica","region":"","article":"Dominica","chart":"0","table":"","index":"0"},
{"country":"Dominican Republic","region":"","article":"the_Dominican_Republic","chart":"0","table":"","index":"0"},
{"country":"East Timor","region":"","article":"East_Timor","chart":"0","table":"","index":"0"},
{"country":"Ecuador","region":"","article":"Ecuador","chart":"0","table":"","index":"0"},
{"country":"Egypt","region":"","article":"Egypt","chart":"0","table":"","index":"0"},
{"country":"El Salvador","region":"","article":"El_Salvador","chart":"0","table":"","index":"0"},
{"country":"Equatorial Guinea","region":"","article":"Equatorial_Guinea","chart":"0","table":"","index":"0"},
{"country":"Eritrea","region":"","article":"Eritrea","chart":"0","table":"","index":"0"},
{"country":"Estonia","region":"","article":"Estonia","chart":"0","table":"","index":"0"},
{"country":"Eswatini","region":"","article":"Eswatini","chart":"0","table":"","index":"0"},
{"country":"Ethiopia","region":"","article":"Ethiopia","chart":"0","table":"","index":"0"},
{"country":"Fiji","region":"","article":"Fiji","chart":"0","table":"","index":"0"},
{"country":"Finland","region":"","article":"Finland","chart":"0","table":"","index":"0"},
{"country":"France","region":"French Guiana","article":"French_Guiana","chart":"0","table":"","index":"0"},
{"country":"France","region":"French Polynesia","article":"French_Polynesia","chart":"0","table":"","index":"0"},
{"country":"France","region":"Guadeloupe","article":"Guadeloupe","chart":"0","table":"","index":"0"},
{"country":"France","region":"Mayotte","article":"Mayotte","chart":"0","table":"","index":"0"},
{"country":"France","region":"New Caledonia","article":"New_Caledonia","chart":"0","table":"","index":"0"},
{"country":"France","region":"Réunion","article":"Réunion","chart":"0","table":"","index":"0"},
{"country":"France","region":"Saint Barthélemy","article":"Saint_Barthélemy","chart":"0","table":"","index":"0"},
{"country":"France","region":"Saint Martin","article":"French_Saint_Martin","chart":"0","table":"","index":"0"},
{"country":"France","region":"Martinique","article":"Martinique","chart":"0","table":"","index":"0"},
{"country":"France","region":"Saint Pierre & Miquelon","article":"Saint_Pierre_and_Miquelon","chart":"0","table":"","index":"0"},
{"country":"France","region":"","article":"France","chart":"0","table":"","index":"0"},
{"country":"Gabon","region":"","article":"Gabon","chart":"0","table":"","index":"0"},
{"country":"Gambia","region":"","article":"Gambia","chart":"0","table":"","index":"0"},
{"country":"Georgia","region":"","article":"Georgia_(country)","chart":"0","table":"","index":"0"},
{"country":"Germany","region":"","article":"Germany","chart":"0","table":"","index":"0"},
{"country":"Ghana","region":"","article":"Ghana","chart":"0","table":"","index":"0"},
{"country":"Greece","region":"","article":"Greece","chart":"0","table":"","index":"0"},
{"country":"Grenada","region":"","article":"Grenada","chart":"0","table":"","index":"0"},
{"country":"Guatemala","region":"","article":"Guatemala","chart":"0","table":"","index":"0"},
{"country":"Guinea","region":"","article":"Guinea","chart":"0","table":"","index":"0"},
{"country":"Guinea-Bissau","region":"","article":"Guinea-Bissau","chart":"0","table":"","index":"0"},
{"country":"Guyana","region":"","article":"Guyana","chart":"0","table":"","index":"0"},
{"country":"Haiti","region":"","article":"Haiti","chart":"0","table":"","index":"0"},
{"country":"Honduras","region":"","article":"Honduras","chart":"0","table":"","index":"0"},
{"country":"Hungary","region":"","article":"Hungary","chart":"0","table":"","index":"0"},
{"country":"Iceland","region":"","article":"Iceland","chart":"0","table":"","index":"0"},
{"country":"India","region":"","article":"India","chart":"0","table":"","index":"0"},
{"country":"Indonesia","region":"","article":"Indonesia","chart":"0","table":"","index":"0"},
{"country":"Iran","region":"","article":"Iran","chart":"0","table":"","index":"0"},
{"country":"Iraq","region":"","article":"Iraq","chart":"0","table":"","index":"0"},
{"country":"Ireland","region":"","article":"Ireland","chart":"0","table":"","index":"0"},
{"country":"Israel","region":"","article":"Israel","chart":"0","table":"","index":"0"},
{"country":"Italy","region":"","article":"Italy","chart":"0","table":"","index":"0"},
{"country":"Ivory Coast","region":"","article":"Ivory_Coast","chart":"0","table":"","index":"0"},
{"country":"Jamaica","region":"","article":"Jamaica","chart":"0","table":"","index":"0"},
{"country":"Japan","region":"","article":"Japan","chart":"0","table":"","index":"0"},
{"country":"Jordan","region":"","article":"Jordan","chart":"0","table":"","index":"0"},
{"country":"Kazakhstan","region":"","article":"Kazakhstan","chart":"0","table":"","index":"0"},
{"country":"Kenya","region":"","article":"Kenya","chart":"0","table":"","index":"0"},
{"country":"Kosovo","region":"","article":"Kosovo","chart":"0","table":"","index":"0"},
{"country":"Kuwait","region":"","article":"Kuwait","chart":"0","table":"","index":"0"},
{"country":"Kyrgyzstan","region":"","article":"Kyrgyzstan","chart":"0","table":"","index":"0"},
{"country":"Laos","region":"","article":"Laos","chart":"0","table":"","index":"0"},
{"country":"Latvia","region":"","article":"Latvia","chart":"0","table":"","index":"0"},
{"country":"Lebanon","region":"","article":"Lebanon","chart":"0","table":"","index":"0"},
{"country":"Liberia","region":"","article":"Liberia","chart":"0","table":"","index":"0"},
{"country":"Libya","region":"","article":"Libya","chart":"0","table":"","index":"0"},
{"country":"Liechtenstein","region":"","article":"Liechtenstein","chart":"0","table":"","index":"0"},
{"country":"Lithuania","region":"","article":"Lithuania","chart":"0","table":"","index":"0"},
{"country":"Luxembourg","region":"","article":"Luxembourg","chart":"0","table":"","index":"0"},
{"country":"Madagascar","region":"","article":"Madagascar","chart":"0","table":"","index":"0"},
{"country":"Malawi","region":"","article":"Malawi","chart":"0","table":"","index":"0"},
{"country":"Malaysia","region":"","article":"Malaysia","chart":"0","table":"","index":"0"},
{"country":"Maldives","region":"","article":"the_Maldives","chart":"0","table":"","index":"0"},
{"country":"Mali","region":"","article":"Mali","chart":"0","table":"","index":"0"},
{"country":"Malta","region":"","article":"Malta","chart":"0","table":"","index":"0"},
{"country":"Mauritania","region":"","article":"Mauritania","chart":"0","table":"","index":"0"},
{"country":"Mauritius","region":"","article":"Mauritius","chart":"0","table":"","index":"0"},
{"country":"Mexico","region":"","article":"Mexico","chart":"0","table":"","index":"0"},
{"country":"Moldova","region":"","article":"Moldova","chart":"0","table":"","index":"0"},
{"country":"Monaco","region":"","article":"Monaco","chart":"0","table":"","index":"0"},
{"country":"Mongolia","region":"","article":"Mongolia","chart":"0","table":"","index":"0"},
{"country":"Montenegro","region":"","article":"Montenegro","chart":"0","table":"","index":"0"},
{"country":"Morocco","region":"","article":"Morocco","chart":"0","table":"","index":"0"},
{"country":"Mozambique","region":"","article":"Mozambique","chart":"0","table":"","index":"0"},
{"country":"Myanmar","region":"","article":"Myanmar","chart":"0","table":"","index":"0"},
{"country":"Namibia","region":"","article":"Namibia","chart":"0","table":"","index":"0"},
{"country":"Nepal","region":"","article":"Nepal","chart":"0","table":"","index":"0"},
{"country":"Netherlands","region":"Aruba","article":"Aruba","chart":"0","table":"","index":"0"},
{"country":"Netherlands","region":"Curaçao","article":"Curaçao","chart":"0","table":"","index":"0"},
{"country":"Netherlands","region":"Sint Maarten","article":"Sint_Maarten","chart":"0","table":"","index":"0"},
{"country":"Netherlands","region":"","article":"the_Netherlands","chart":"0","table":"","index":"0"},
{"country":"Netherlands","region":"Sint Eustatius","article":"Sint_Eustatius","chart":"0","table":"","index":"0"},
{"country":"New Zealand","region":"","article":"New_Zealand","chart":"0","table":"","index":"0"},
{"country":"Nicaragua","region":"","article":"Nicaragua","chart":"0","table":"","index":"0"},
{"country":"Niger","region":"","article":"Niger","chart":"0","table":"","index":"0"},
{"country":"Nigeria","region":"","article":"Nigeria","chart":"0","table":"","index":"0"},
{"country":"Niue","region":"","article":"Niue","chart":"0","table":"","index":"0"},
{"country":"North Macedonia","region":"","article":"North_Macedonia","chart":"0","table":"","index":"0"},
{"country":"Norway","region":"","article":"Norway","chart":"0","table":"","index":"0"},
{"country":"Oman","region":"","article":"Oman","chart":"0","table":"","index":"0"},
{"country":"Pakistan","region":"","article":"Pakistan","chart":"0","table":"","index":"0"},
{"country":"Palestine","region":"","article":"Palestine","chart":"0","table":"","index":"0"},
{"country":"Panama","region":"","article":"Panama","chart":"0","table":"","index":"0"},
{"country":"Papua New Guinea","region":"","article":"Papua_New_Guinea","chart":"0","table":"","index":"0"},
{"country":"Paraguay","region":"","article":"Paraguay","chart":"0","table":"","index":"0"},
{"country":"Peru","region":"","article":"Peru","chart":"0","table":"","index":"0"},
{"country":"Philippines","region":"","article":"the_Philippines","chart":"0","table":"","index":"0"},
{"country":"Poland","region":"","article":"Poland","chart":"0","table":"","index":"0"},
{"country":"Portugal","region":"","article":"Portugal","chart":"0","table":"","index":"0"},
{"country":"Qatar","region":"","article":"Qatar","chart":"0","table":"","index":"0"},
{"country":"Romania","region":"","article":"Romania","chart":"0","table":"","index":"0"},
{"country":"Russia","region":"","article":"Russia","chart":"0","table":"","index":"0"},
{"country":"Rwanda","region":"","article":"Rwanda","chart":"0","table":"","index":"0"},
{"country":"Saint Kitts & Nevis","region":"","article":"Saint_Kitts_and_Nevis","chart":"0","table":"","index":"0"},
{"country":"Saint Lucia","region":"","article":"Saint_Lucia","chart":"0","table":"","index":"0"},
{"country":"Saint Vincent and the Grenadines","region":"","article":"Saint_Vincent_and_the_Grenadines","chart":"0","table":"","index":"0"},
{"country":"San Marino","region":"","article":"San_Marino","chart":"0","table":"","index":"0"},
{"country":"São Tomé & Príncipe","region":"","article":"São_Tomé_and_Príncipe","chart":"0","table":"","index":"0"},
{"country":"Saudi Arabia","region":"","article":"Saudi_Arabia","chart":"0","table":"","index":"0"},
{"country":"Senegal","region":"","article":"Senegal","chart":"0","table":"","index":"0"},
{"country":"Serbia","region":"","article":"Serbia","chart":"0","table":"","index":"0"},
{"country":"Seychelles","region":"","article":"Seychelles","chart":"0","table":"","index":"0"},
{"country":"Sierra Leone","region":"","article":"Sierra_Leone","chart":"0","table":"","index":"0"},
{"country":"Singapore","region":"","article":"Singapore","chart":"0","table":"","index":"0"},
{"country":"Slovakia","region":"","article":"Slovakia","chart":"0","table":"","index":"0"},
{"country":"Slovenia","region":"","article":"Slovenia","chart":"0","table":"","index":"0"},
{"country":"Somalia","region":"","article":"Somalia","chart":"0","table":"","index":"0"},
{"country":"South Africa","region":"","article":"South_Africa","chart":"0","table":"","index":"0"},
{"country":"South Korea","region":"","article":"South_Korea","chart":"0","table":"","index":"0"},
{"country":"South Sudan","region":"","article":"South_Sudan","chart":"0","table":"","index":"0"},
{"country":"Spain","region":"","article":"Spain","chart":"0","table":"","index":"0"},
{"country":"Sri Lanka","region":"","article":"Sri_Lanka","chart":"0","table":"","index":"0"},
{"country":"Sudan","region":"","article":"Sudan","chart":"0","table":"","index":"0"},
{"country":"Suriname","region":"","article":"Suriname","chart":"0","table":"","index":"0"},
{"country":"Sweden","region":"","article":"Sweden","chart":"0","table":"","index":"0"},
{"country":"Switzerland","region":"","article":"Switzerland","chart":"0","table":"","index":"0"},
{"country":"Syria","region":"","article":"Syria","chart":"0","table":"","index":"0"},
{"country":"Taiwan","region":"","article":"Taiwan","chart":"0","table":"","index":"0"},
{"country":"Tanzania","region":"","article":"Tanzania","chart":"0","table":"","index":"0"},
{"country":"Thailand","region":"","article":"Thailand","chart":"0","table":"","index":"0"},
{"country":"Togo","region":"","article":"Togo","chart":"0","table":"","index":"0"},
{"country":"Trinidad & Tobago","region":"","article":"Trinidad_and_Tobago","chart":"0","table":"","index":"0"},
{"country":"Tunisia","region":"","article":"Tunisia","chart":"0","table":"","index":"0"},
{"country":"Turkey","region":"","article":"Turkey","chart":"0","table":"","index":"0"},
{"country":"Uganda","region":"","article":"Uganda","chart":"0","table":"","index":"0"},
{"country":"Ukraine","region":"","article":"Ukraine","chart":"0","table":"","index":"0"},
{"country":"United Arab Emirates","region":"","article":"the_United_Arab_Emirates","chart":"0","table":"","index":"0"},
{"country":"United Kingdom","region":"Bermuda","article":"Bermuda","chart":"0","table":"","index":"0"},
{"country":"United Kingdom","region":"Cayman Islands","article":"the_Cayman_Islands","chart":"0","table":"","index":"0"},
{"country":"United Kingdom","region":"Channel Islands","article":"Channel_Islands","chart":"0","table":"","index":"0"},
{"country":"United Kingdom","region":"Gibraltar","article":"Gibraltar","chart":"0","table":"","index":"0"},
{"country":"United Kingdom","region":"Isle of Man","article":"the_Isle_of_Man","chart":"0","table":"","index":"0"},
{"country":"United Kingdom","region":"Montserrat","article":"Montserrat","chart":"0","table":"","index":"0"},
{"country":"United Kingdom","region":"","article":"United_Kingdom","chart":"0","table":"","index":"0"},
{"country":"United Kingdom","region":"Anguilla","article":"Anguilla","chart":"0","table":"","index":"0"},
{"country":"United Kingdom","region":"British Virgin Islands","article":"the_British_Virgin_Islands","chart":"0","table":"","index":"0"},
{"country":"United Kingdom","region":"Turks & Caicos Islands","article":"the_Turks_and_Caicos_Islands","chart":"0","table":"","index":"0"},
{"country":"United Kingdom","region":"Falkland Islands","article":"the_Falkland_Islands","chart":"0","table":"","index":"0"},
{"country":"United States","region":"","article":"United_States","chart":"0","table":"","index":"0"},
{"country":"Uruguay","region":"","article":"Uruguay","chart":"0","table":"","index":"0"},
{"country":"Uzbekistan","region":"","article":"Uzbekistan","chart":"0","table":"","index":"0"},
{"country":"Vatican City","region":"","article":"Vatican_City","chart":"0","table":"","index":"0"},
{"country":"Venezuela","region":"","article":"Venezuela","chart":"0","table":"","index":"0"},
{"country":"Vietnam","region":"","article":"Vietnam","chart":"0","table":"","index":"0"},
{"country":"Western Sahara","region":"","article":"Western_Sahara","chart":"0","table":"","index":"0"},
{"country":"Yemen","region":"","article":"Yemen","chart":"0","table":"","index":"0"},
{"country":"Zambia","region":"","article":"Zambia","chart":"0","table":"","index":"0"},
{"country":"Zimbabwe","region":"","article":"Zimbabwe","chart":"0","table":"","index":"0"}];